### ISSUE TITLE
Participants: No import of sample data

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1170]
`.../participants/import`

### Description
While importing, it should be checked if the uploaded import file contains the sample data from the sample file. This sample data should not be imported. In the preview it should be shown that these lines are examples and therefore these lines are not imported.

For whatever reason, some people leave the sample data in the CSV file. Unfortunately, this data is then imported into the meeting.

**Comment by jsangmeister** [comment]
I'm against adding this feature - I, as a user, would like to be able to try out the import with the example data (e.g. in the demo) and not be blocked by the app itself.

If users do not want to use the application correctly, there is a point where it is their own fault...

**Comment by luisa-beerboom** [comment]
> I'm against adding this feature - I, as a user, would like to be able to try out the import with the example data (e.g. in the demo) and not be blocked by the app itself.
> 
> If users do not want to use the application correctly, there is a point where it is their own fault...

I agree completely. It is not our problem if people do not delete example data from their import files. 
This kind of "fix" would just further bloat the already overgrown import services and be just more trouble than it's worth in general.

I can see however that this may be a security issue in case of the participant import (That example file contains a meeting admin user with a defined initial password). If an admin user is unintentionally created by forgetting to delete the example data, bad actors that are familiar with OpenSlides may infiltrate that meeting by trying out that user name with the given password. This will (in the worst case) allow them to sabotage massive meetings with hundreds of users while they are running.
We should at least add a warning to that import or think about how we can otherwise make it securer.
