### ISSUE TITLE
OS3 import of a large event timed-out

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1388]
The import of a large OS3 event into OS4 aborts after some time (approx. 4min). An error message is displayed in the console. 

Error message: 
![Screenshot_20220718_140526](https://user-images.githubusercontent.com/105491030/179508072-872a68db-e056-4ca4-be65-cbbd98a9b898.png)

For Reproduction I have put an example file in https://testintern.openslides.com/69/mediafiles. 

Reproduction:
1. download example file
2. open committees in dashboard
3. select committee or create new one
4. open three point menu and import meeting
5. select downloaded file
6. wait until error appears

What should happen: The file is imported without errors and the user gets feedback that the program is still working until the import is complete. The feedback could be for example a spinning wheel or a Knight Rider bar.

**Comment by jsangmeister** [comment]
This is known and not easy to fix (I'm guessing the timeout for the testintern instance is also raised to 240 seconds @emanuelschuetze?). @r-peschke is currently working on a workaround. Since we track the progress in https://github.com/OpenSlides/openslides-backend/issues/1137 and the corresponding PR, I will close this.
