### ISSUE TITLE
category selection is missing during motion creation as e.g. delegate

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1408]
In OS3, for example, it was possible as a delegate to select a category (Sachgebiet) when creating a motion. This option is missing in OS4. 

Reproduction:
1. open a meeting as a delegate with the right to create motions
2. go to menu Motions
3. click on the plus-symbol and a create a new motion

What should happen: From my point of view, the option should be available, so the admins of a meeting could decide if they want to use it. It may be possible to integrate this as a setting option in the motion settings.

Example image:
left side OS4 - right side OS3
![Screenshot_20220720_091648](https://user-images.githubusercontent.com/105491030/179922263-70308743-096e-49f0-a3e6-766d3d3c165f.png)

**Comment by luisa-beerboom** [comment]
I've looked into it and currently that field is present, but only for users with the `motionCanManage` permission.

It seems that the backend doesn't allow for any other user to add categories during creation, which is why there is no point in implementing that field there.
As I have only a vague idea why that field may be restricted, maybe this should be further discussed with the backend-people, but as a client issue this is currently impossible to solve.

**Comment by MSoeb** [comment]
Done some investigation why the field is missing in OS4: in https://github.com/OpenSlides/OpenSlides/wiki/motion.create#permissions is a description about an exception, that describe a situation when the field is not visible. That description didn't include the possibility to create a motion. The field should be visible for anyone creating a motion like in OS3. I think that the field was unintentionally forgotten to integrate.
