### ISSUE TITLE
Missing German translations

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1409]
Various word groups and words lack a German translation. Below is a list:

- [x] 'List of speakers countdown' (Found in: Projector/Default projector details/Countdowns) -> Translation: Countdown Redeliste
- [x] 'voting countdown' (Found in: Projector/Default projector details/Countdowns) -> Translation: Countdown Abstimmung
- [x] ~~Mail body for Login mail (Found in:Setting/Participants/Email/Email body) -> By switching language to german, the whole email body should be in German (compare OS3 demo)~~
- [x] 'base folder' ( Found in: /mediafiles/upload ) -> Translation like in OS3 'Hochladen in:   Basisverzeichnis'
- [x] ~~"Fehler: data.is_active must be boolean or null" - Found in: user csv import~~
- [x] ~~"Fehler: data.is_physical_person must be boolean or null" - found in: user csv import~~
- [x] ~~"Fehler: data.gender must be one of ['male', 'female', 'diverse', None]" - found in user csv import~~
- [x] in workflows several editing menus use english instead of german terms. for example: open motions/three-dot-menu/workflow/easy workflow/ and edit "eingereicht". the menu is in english.

If other translations are missing, they will be added to the issue.

**Comment by jsangmeister** [comment]
> Mail body for Login mail (Found in:Setting/Participants/Email/Email body) -> By switching language to german, the whole email body should be in German (compare OS3 demo)

This is kinda hard: We could theoretically just translate the body in the client, but the email which will be sent would still be in english, which would be quite confusing. The alternative is to implement translation ability in the backend, which is tracked in https://github.com/OpenSlides/openslides-backend/issues/994, but currently not highly prioritized. We could talk about changing this priority, but removing it for now from this issue.

> "Fehler: data.is_active must be boolean or null" - Found in: user csv import

We currently do not translate errors which come from the backend, as far as I know. These errors should (in theory) seldom reach the user, since the client should be in sync with the backend and catch the same errors. The ones you listed are all because of bugs in the client, which will be solved in https://github.com/OpenSlides/openslides-client/issues/1406. So, unless we want to implement generic translation of backend error messages in the client, which would require a lot of work, I will remove these as well.

**Comment by jsangmeister** [comment]
closing this since all open tasks are done. The aforementioned points are tracked in the backend. Feel free to open a new issue is anything else pops up.
