### ISSUE TITLE
Users cannot be deleted from a meeting

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1419]
Currently it is not possible to delete a user from a meeting. Neither by multiple selection nor in the user detail view. When deleting, an error message appears at the bottom of the screen and in the console.

Repro:
1. open a meeting
2. go to participants and create via plus icon a user
3. try to delete the user in details view and via multi selection

Fun fact: As a superadmin i got kicked back to the dashboard if i try to deleted a user in the detail view. 

Affected OS4 Version: 4.0.0-beta-20220718-996743f and todays nightly build

What should happen: Users can be deleted. 

![Screenshot_20220720_145243](https://user-images.githubusercontent.com/105491030/179986842-128ca2ea-0e8d-4406-b798-453ef8ee404e.png)

**Comment by luisa-beerboom** [comment]
So you deleted the user in one view, saw that he was still in the list and then attempted to delete him again, getting you this error? (I will assume that this is what happened, since that is the only way I could replicate that error)
The cause of this is a problem that currently exists between the autoupdate service and the client. The client, for some reason, is currently not receiving updates on deleted users from the autoupdate service. Since these deletions do not get reported, clients currently have no way of knowing, if the users in their browser storage have been deleted. That's why deleted users remain in the userlist.
Since the client still thinks that the user exists, he will still permit you to perform actions on that user, read his data and so on, but if he sends an action concerning that user to the backend, the backend will naturally send errors.

@MSoeb  Currently if you want to check if your deletions happen, I would advise to reload the list. That reloads all data and you will see that the user whom you have "failed" to delete is actually gone.

For now I will look into the behaviour where attempting to delete a user from the detail view gets you thrown out of the meeting. The updating issue will sadly have to wait, until there's a solution for the autoupdate problem

**Comment by luisa-beerboom** [comment]
Will be covered by solutions to #1444 and #1344
