### ISSUE TITLE
when autopilot right is revoked, user continues to see updates in autopilot

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1421]
If a user's permission to use the autopilot is revoked during a meeting, but he remains in this menu, he will continue to see all updates projected into the autopilot. Only by manually leaving the autopilot he has no further access rights.

Reproduction:
Reproduction requires two users; an admin and another user in the Delegates group.

1. Both users must be logged into the meeting in differnent browsers.
2. delegate opens autopilot
3. admin projects a motion
4. admin removes delegate autopilot rights in group rights menu. 
5. Admin projects another motion. Delegate sees update in autopilot.

What should happen from my point of view: When a user is revoked the permission to see the autopilot, the user should be automatically navigated to the home page to not see any more updates.

**Comment by jsangmeister** [comment]
Automatic redirection on permission loss is something we've never done, AFAIK. The same thing would be needed for all other views, e.g. motions, agenda, etc., when the respective rights are revoked.

The continuing autoupdates happend because the autopilot just wraps some other OS functionality which has its own access rights, e.g. the projector is controlled by `projector.can_see`. So it is logical that the user continues to see updates, since he is permitted to do so.

**Comment by luisa-beerboom** [comment]
This is basically just a sub-problem of #1439 so I'll close this as a duplicate
