### ISSUE TITLE
Set meeting for a user on account level via multiple selection overwrites group inside the meeting

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1441]
If a user exists in a meeting and is added to the same meeting again at the dashboard level via multiple selection, the previous group assignment is overwritten.

This is very problematic, especially for administrators, as it causes them to unintentionally lose their status.

Reproduction: For testing is a committee with a meeting needed.
1. open meeting, go to participants, create a new one and add it to group admin
2. open in new tab the dashboard and head to accounts
3. open the three-dot-menu and choose mulitselect. 
4. search for the desired user in search box, select user, click again on the three-dot-menu, choose set/remove meeting and set user to the meeting which is open in other tab
5. open other tab again, go to participants in navigation bar and check the group of the user. 

What should happen: When multiple selections are made, there should be a check that prevents the accounts from being added again, thus preventing them from being overwritten. Groups shold not be overwritten for user that exist in meeting.

**Comment by jsangmeister** [comment]
Situation: User is in group A of meeting 1. Via multiselect he is added to group B of meeting 1. The intended behaviour you described would not add the user to any group, but leave him in just group A. I would argue that it's more intuitive to add him to group B, but keep him in group A.

**Comment by MSoeb** [comment]
Fix didn't work. Group is still overwritten.

Additionally: If you want to add participants to a meeting via accounts, this is no longer possible. Existing groups are no longer recognized. An error appears: Fehler: Didn't find a group with groupname Delegierte in any meeting.

**Comment by luisa-beerboom** [comment]
> Additionally: If you want to add participants to a meeting via accounts, this is no longer possible. Existing groups are no longer recognized. An error appears: Fehler: Didn't find a group with groupname Delegierte in any meeting.

Aside from the fact that I didn't even touch that feature in this PR, that behaviour is to be expected, since a group `Delegierte` probably doesn't exist in your instance. When adding a user to a meeting via accounts you have to enter the base name of the group as it is saved in the database, note: **The client always translates group names from English to your selected language, also the pre-programmed group names are all saved in English.** This means that if you want to add a user to the group `Delegierte` you have to enter the name that you'd find for this group if you change your instances language to English (probably `Delegates`). There should be a notice about that on the wizard itself.

I'll take a look at why the group is still overwritten though.
