### ISSUE TITLE
Remove setting "sort name of participants by"

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1467]
(Updated description)

The setting "sort name of participants by" is no longer needed and should be removed from all views and models (probably just the settings view and the meeting model).

**Comment by luisa-beerboom** [comment]
Two things:

1. The reason why this option does not work, seems to be because it simply is not used anywhere.
2. The sorting rules are currently saved in the local storage and reloaded whenever the page is opened again. Considering that it would probably be annoying for the user if their selected settings arbitrarily got changed (maybe even while he is trying to look through the participant list), just because some administrator decided to use a different setting, I think the only realistic utilization of this value would be in order to set a default value for the list, which would only affect users when they open the view for the first time (or after emptying the cache).

We should probably discuss, what this option should actually do before touching it

**Comment by jsangmeister** [comment]
> I think the only realistic utilization of this value would be in order to set a default value for the list, which would only affect users when they open the view for the first time

I agree, and this is basically the same case as in the "tiles vs. list" discussion for the motion list, so I would argue to remove the option completely.

**Comment by jsangmeister** [comment]
I don't think there are any. I will change this issue accordingly and open one in the backend.
