### ISSUE TITLE
voting rights delegation: UI not coherent 

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1533]
**Problem:** The UI for **_voting rights received from (principals)_** and **_voting rights delegated to (proxy)_** are not coherent. First has checkboxes  and the other bullet points.

_voting rights received from (principals) - UI_
![Screenshot_20220825_143402](https://user-images.githubusercontent.com/105491030/186665794-436aa6ea-74ce-4c14-9437-7c6f7ab14171.png)

_voting rights delegated to (proxy) - UI_
![Screenshot_20220825_143422](https://user-images.githubusercontent.com/105491030/186665841-0b90a8ef-3620-4613-836a-761d06ec9937.png)

**Reproduction:**
1. open a meeting
2. open participants
3. click on one participant
4. under meeting information you could find the selection menus

**What should happen:**
The UI of both selection boxes should have checkboxes, because they are easier to use.

**Comment by jsangmeister** [comment]
This should be intended and it makes sense: You can delegate your vote to one and only one user, hence the "normal" selector list without checkboxes. But you can receive delegations from multiple users, hence the checkboxes. Since checkboxes always indicate that multiple options can be selected, I'm against introducing them in the second selector.

**Comment by MSoeb** [comment]
Good point. I will close the issue.
