### ISSUE TITLE
Additional infos in motion forward dialog

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1576]
Show current status of the selected motion in the header of the motion forward dialog and in the list of meetings the committee should be explicitly visible behind the meeting name.

**Comment by luisa-beerboom** [comment]
@rrenkert  I believe the meetings are already sorted into titled paragraphs by committee. Is there really a need to put the committee name behind the meeting name as well?

Also:
Since it is possible to forward multiple motions at once via multiselect, what shall be done about the status in the header? It would be very confusing to put multiple status in there at once, especially without any sort of relation to the corresponding motion.
We could decide to only do this for single motion forwardings.
We could also move this information to the dialogs content (maybe something like "<title> - <status>"?).

**Comment by rrenkert** [comment]
Good points. Lets talk about this with @emanuelschuetze to discuss the requirements.

**Comment by luisa-beerboom** [comment]
Update after talkong with @emanuelschuetze 

- no additional committee names after meeting names
- put two new lines: state (only for single forwardings) and submitter (i.e. the name of the submitter that will be used for the forwarded motion => the name of the current committee) these should be fixated below the dialog title and always visible (even when scrolling)
- scrollbar activates too early in chrome
