### ISSUE TITLE
List of speakers projection problems

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1614]
* Create new Agenda item
* Create new projector for list of speakers
* Project list of speakers

Result: List of speakers is empty; Subtilte contains "0 speakers"
Expected: Show speaker count only if >0

* Add Speaker
* Start and stop 

Result: The speaker remains in the list even though the setting "Number of last speakers to be shown on the projector" ist set to 0.
Expected: List should be empty.

**Comment by MSoeb** [comment]
Issue need to be reopened, because the last speaker on the slide of List of speakers are still visible after the speech is stopped. The user is only grayed ou, but still visible.

![Screenshot_20221024_113424](https://user-images.githubusercontent.com/105491030/197496321-7522a8e0-d8e9-42cf-bc1e-b920e5f906f2.png)

Reproduction:
1. open meeting
2. open agenda
3. create a new a agenda item by clicking on the plus-icon. 
4. project the new agenda item to standardprojector by clicking on the camera icon in the new agenda item line. 
5. open the autopilot and add some users . at least two - to the speaker list. 
6. open projector
7. create a list of speakers projector. open it. click on current list of speakers and click on the slide icon.
8. now go back to the autopilot and start and stop a speech
9. head back to the list of speakers projector. a grayed out user should appear. 

Expected behavior: If the current speaker is stopped, he will be deleted from the list of speakers and is not visible anymore.

**Comment by luisa-beerboom** [comment]
With the way it is displayed this doesn't seem to be a loading error to me

When looking into it the code, the list of speakers slide looks like this:

- list of all past speakers (grey)
- current speaker (with mic icon)
- list of the next speakers (as a list with row numbers)

This "bug" seems to be in line with that

Could it be that this is just not supposed to show for the _current_ list of speakers? 
Or is this actually supposed to be there (in which case I've noticed that the slide is not always showing all of the past speakers)?

**Comment by MSoeb** [comment]
Yes, I've meant the current list of speaker in the projector. There the grayed out last speakers should not be visible like OS3 handles this.

Does this answers you questions? :)

**Comment by bastianjoel** [comment]
@MSoeb There is a "Number of last speakers to be shown on the projector". Could you check if this is set to "0"? 
I can't replicate the issue with that setting set to "0"
