### ISSUE TITLE
Motion forward dialog will pre-select demo meeting

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1652]
1. Open dev-instance with demo meeting
2. create a committee that can also forward to the demo committee
3. when trying to forward a motion from that committee, the dialog will pre-select the demo meeting

This is probably because the demo has some sort of flag that can't be set in the client any more

**Comment by jsangmeister** [comment]
This was a feature rather than a bug; the only problem seemed to be that the client could not set the `committee/default_meeting_id`. But the relation still exists in the backend and now does nothing. Either we reintroduce the feature properly in the client (@emanuelschuetze I mean to remember that you explicitely wanted a default meeting so one does not have to scroll/search through potentially hundreds of meetings of a committee?) or we also remove it in the backend if there is no need for this feature.

**Comment by emanuelschuetze** [comment]
Please keep feature in backend. We will reintroduce this feature in client later (4.x).
