### ISSUE TITLE
Vote weight is not displayed

### ISSUE THREAD

**Issue by m-schieder** [OpenSlides/openslides-client#1671]
-  Activate Vote weight
-  Delete the storage of the page via the Applicatins page of the browser
-  Press F5
-  Log in again
-  Go to the Participants list page

    -> Vote weight is not displayed, not even on the detailed view or on the edit view
 
 * Press F5 again on one of the broken pages and the vote weight is there again

In version 4.0.0-beta-20220916-f31311f the error does not exist.

**Comment by luisa-beerboom** [comment]
I've analysed this from the client.
The problem looks as follows:

1. The `ParticipantListComponent` calculates whether it should show vote weight as `isElectronicVotingEnabled && voteWeightEnabled`
2. This doesn't work because the value for `isElectronicVotingEnabled` isn't loaded correctly by the `OrganizationSettingsService`
3. Which is pulling it from the models
4. Which should be filled with data by autoupdates
5. The autoupdate requests apparently contain these settings, but the responses don't contain the corresponding data

Which means: 
Something happens either on the clients side, or that on the autoupdates side that stopps the autoupdate from sending the value for `enable_electronic_voting`.

**Comment by luisa-beerboom** [comment]
@ostcar do you have any idea what might explain this behaviour? Something that the client may not be sending/doing in regards to the backend that would stop the autoupdate from sending these specific values (The autoupdate is still sending data for other organization fields and, of course this bug does only happen with this specific setup)

**Comment by jsangmeister** [comment]
I inspected this as well, and to me this looks like something broke with the new autoupdate worker, especially considering that it still worked two releases ago and it works in some cases, but in others not. It also looks like the worker is grouping some requests (maybe incorrectly?):

When you load the page normally, the requests for the organization and the operator are both sent before a response is received. Then, the response for both streams (operator and organization) is the same and contains both models.

When you initially enter the page after clearing the page data, the response of the organization stream is received before the operator stream is requested. This (somehow) leads to the missing data, although I'm not quite sure how, but I suspect it has something to do with the bundling of the request. Maybe @bastianjoel can take a look at this.

**Comment by ostcar** [comment]
I don't think that the autoupdate-service is responsible for this. The only thing to notice is, that the field `enable_electronic_voting` is in restriction_mode `B`. So it can only be seen for logged in users. I don't know if this is relevant. But it the bug report it says that you have to "Log in again". So at least for a moment the user is anonymous and can not see the field.

If you think that the autoupdate-service is responsible, then please paste the autoupdate-request, the response and what you would expect instead.

**Comment by luisa-beerboom** [comment]
I don't know how the autoupdate checks for authentification, but for now I don't know if this is actually an autoupdate problem.

The part about not being logged in may perhaps be the root cause:

I tried the following:
1. Make sure you're logged out
2. Close all OpenSlides tabs
3. Open a new tab
4. Navigate to the participant list of a meeting directly by entering the url `<instance-url>/<meetingId>/participants`
5. Use the login screen that will appear to log in with an account that is in that meeting
6. navigate to the participant list of that meeting
7. same bug: no visible voteweight

i.e.
1. the participant list is visited without login => the client automatically navigates to login
2. the user logs in
3. he navigates to the same participant list
4. bug appears

It seems to me as if the client is maybe attempting to request this data from the autoupdate when the page is initially opened (before he is re-routed to the login page and when he is therefore still logged out). This subscription (and it's restrictions) may then persist beyond the reroute and login into the legitimate visit to the page.
I would suspect that it may have something to do with the service workers, because they are a very recent change to the way in which autoupdates were handled.

**Comment by ostcar** [comment]
When a new request is sent to the autoupdate-service, the request header contains a cookie and an auth-token. (This is the same for the backend or any other service). The autoupdate-service uses this information to get the request user id.

It is technically not possible to change the request user after the request is open.  When you logout or login (or change the request user in another way), you have to close and reopen all requests to the autoupdate-service. Its the same for the ICC service or any other long living request (currently, it should only be these two service, but we might add others in the future).

From your description, there could be an error in the communication between the auth-service and the autoupdate-service. Because if a user logs out, his session should be invalidated. In this situation, all requests to the autoupdate service should be closed from the server side. But this only works for logout. For a login, the client has to do this manually.

**Comment by m-schieder** [comment]
@luisa-beerboom The error came in the client with a7733e1

**Comment by luisa-beerboom** [comment]
If that's the case maybe @bastianjoel really _should_ be the one to look at this

**Comment by bastianjoel** [comment]
> Because if a user logs out, his session should be invalidated. In this situation, all requests to the autoupdate service should be closed from the server side. But this only works for logout. For a login, the client has to do this manually.

I've missed adding logic to restart the currently open streams after logging in when moving the authentication process into the worker.
