### ISSUE TITLE
Check new permissions for orga-layer

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#174]
Check, if all new permissions for the orga-layer is already implemented in the client.

**Comment by FinnStutzenstein** [comment]
The meeting-level permissions should work as in OS3. It is mainly the operators `hasPerms` and the three `isInGroup` derivatives. They are all meeting-specific. The operator uses the active meeting service, so someone using the operator does not need to pass in the meeting.

The permissions in the committee- and orga-level are not implemented (to my knowledge). See [OML](https://github.com/OpenSlides/OpenSlides/wiki/Permission-System#organisation-management-level-oml) and [CML](https://github.com/OpenSlides/OpenSlides/wiki/Permission-System#committee-management-level-cml). It needs to be implemented. I suggest to create two enums with all OMLs/CMLs (also the "default" ones) and two functions receiving a OML/CML and returning true, if the operator's OML/CML is equal or higher. Also a directive similar to os-has-perms would be good.

Multiple things to do:
- Check the operator code: What happens, if `hasPerms`, ... (meeting specific function) are called without an active meeting. It has to be handled correctly (return negative results and a console.error or so). This might happen due to two reasons:
  1. A developer uses these functions outside of the meeting scope
  2. Some timing-stuff: You navigate out of a meeting and for a millisecond, there is no active meeting id, but due to CD `hasPerms` is called a last time or so.
- (Just an idea, I do not have a usecase yet, so defer the implementation) Maybe add a possibility to give a different meeting to `hasPerms`, ... so these functions can be used to check permissions in meetings. Maybe useful for checking perms for a meeting, if the user is still in the committee-detail/meeting-list.
- Implement OML/CML
- add a similar directives to os-has-perms for OML/CML
