### ISSUE TITLE
"Create meeting" button does not work in Safari

### ISSUE THREAD

**Issue by GoblinMage** [OpenSlides/openslides-client#1842]
As written in the title, since the past 3 days, the "+"-button to create a new meeting within a committee does not work. Docker-logs aren't giving out any indicators or pointers, that there has been an error or even an attempt to start the action.

The "import meeting"-Button also stopped working.

By now I have rebuild my whole Openslides-Setup several times with no changes to show. Is there something broken with my installation? Is this a known issue? I can't seem to find other people on here with the same problem.

**Comment by jsangmeister** [comment]
This seems rather strange, in the demo (https://demo.os4.openslides.com/) and locally it all works as intended. Did you change anything about your setup 3 days ago (server oder client side)? Like a new update to any dependency, a new browser, a browsere update...

Another test: Did you try and revert your installation to the version where it last worked (i.e. the commit/release from 3+ days ago)? Because if that does not help, there is most likely something wrong externally and not within the OS stack.

**Comment by GoblinMage** [comment]
Hey! It was indeed my browser... I just switched from Firefox to Safari. I tried Firefox again and creating a meeting works flawlessly there. Does that mean OpenSlides doesn't play well with Safari/MacOS? That would be really unfortunate...

Is that a known circumstance? Every other Function in Safari works, only "Create meeting" doesn't.

**Comment by jsangmeister** [comment]
It is known now ;) We've had a couple of small problems with safari in the future, so to be safe I would recommend to use another up-to-date browser. But we will investigate this problem when we have the time

**Comment by luisa-beerboom** [comment]
I found the solution and since the search for the bug was headache inducing, I will state for the record (in case this happens again): 

The `meeting-edit.component.ts` that was supposed to be opened by this button contained a regExp containing `(?<!\/)` (i.e. a negative lookbehind). This is not supported by safari.

What happened was:
1. Negative lookbehind is not supported by safari
2. Therefore the javascript for the `meeting-edit.component` could not be loaded/generated (idk which step failed exactly)
3. As a result the navigation failed with the `router.events` showing a timeout-related `ChunkLoadError`
