### ISSUE TITLE
Show correct error message if sending a mail failed

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1971]
The backend sends a message in the response if sending a an email failed for some reason. This message should be used to fill the snackbar showing the failure.
#1970 can be used to cause an error and the backend sends an appropriate message.

**Comment by luisa-beerboom** [comment]
I would advise to expand the clients `error-map.service` with a new `ErrorMap` for backend errors in order to solve this.

**Comment by luisa-beerboom** [comment]
By the way: @rrenkert 
Is this issue about saving new email addresses, or is it about actually sending emails? 
If it is the latter, please add some example(s) for how to trigger the sending of an email from the client, so that the corresponding backend action can at least be inferred.

The verbose error-text would also be appreciated.

Aimlessly digging around in the backend code to find out which error needs to be caught, does not seem like a sensible use of anyone's time.

**Comment by jsangmeister** [comment]
These messages don't look so nice, let me update them first

**Comment by jsangmeister** [comment]
Updated in https://github.com/OpenSlides/openslides-backend/pull/1618. Keep in mind that once https://github.com/OpenSlides/openslides-backend/pull/1502 is merged, the backend will be able to translate these errors by itself, so you don't want to put took much work into translating these, if that's also part of this issue.

**Comment by luisa-beerboom** [comment]
> the backend will be able to translate these errors by itself, so you don't want to put took much work into translating these, if that's also part of this issue.

Sounds like the http.service and the error-map.service will have to be rewritten in the future to somehow recognise pre-translated error messages.
