### ISSUE TITLE
Forwarding of a motion: sometimes an admin (or user) can't see content because of different workflows

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1979]
**Description:** When forwarding motions, for example, an admin is not be able to see the content of the motion in the target event because an access restriction has been set in the workflow that limits the visibility of the motion to the creator. When the admin clicks on the forward link in the source event or opens it in the target meeting motions list, he sees only the shell of the motion, without any text or justification.

I assume that this phenomenon can also occur in other groups and access restrictions combinations.

The important thing is that the workflow in the target event limits the visibility in the first status, thus giving users the impression that it is a bug.

**Source meeting motion content:**
![Screenshot_20230127_134917](https://user-images.githubusercontent.com/105491030/215091059-f62c1c47-4b4e-4575-9e89-8b5486dd852a.png)

**Target meeting motion content:**
![Screenshot_20230127_134854](https://user-images.githubusercontent.com/105491030/215091172-62128502-cfad-4469-b972-a7c983effbd8.png)

**Reproduction:**
It needs two meetings with the same meeting admin in both meetings. NOT a superadmin. Also the meetings should have the possibility to forward and receive motions. The motion workflow needs to be complex. 
1. open meeting A as a superadmin. go to motions > three-dot-menu > workflows > complex workflow > status in progress > change restrictions to submitters
2. open meeting B and create as the superadmin a new motion with content and justification.
3. change the status of the motion to a level which allows a forwarding. -> forward the motion to meeting A.
4. open as the meeting admin meeting A and check the forwarded motion. No text should be available. 

**What should happen:**
If an admin (or user) does not have access to a forwarded motion, they should receive an error message when opening the motion that they are not allowed to see this content because an access restriction is placed. This would help in evaluating why one cannot see the motion content.

**Comment by bastianjoel** [comment]
It is not completely clear to me why meeting admins are even restricted by the `is_submitter` rule. Also it makes absolutely no sense that they can only see some fields of forwarded motions in a certain state but are able to change that state themselves. 

I could add a message if that field is empty or the permissions are missing but I think think it would be better to adjust the restrictor.

**Comment by ostcar** [comment]
I can not reproduce this. When I follow your steps, the meeting Admin of Meeting A can see the full motion of Motion, that was forwarded from Meeting B

**Comment by bastianjoel** [comment]
Within the reproduction steps it is missing that the motion workflow needs to be set to complex.

**Comment by MSoeb** [comment]
@bastianjoel thx. I've added the information.

**Comment by ostcar** [comment]
I still can not reproduce this. 

There are now two motions. The original in meeting A and the forwarded motion in meeting B.

The meeting Admin of meeting A can see the full forwarded motion. He can not click on "Herkunft » B". If he opens the link of the original motion anyway, he gets the message, that he should not be there.

**Comment by ostcar** [comment]
I was able to reproduce the bug in another way.

I also set the restriction of the original motion in Meeting B to submitters. Then I put the meeting admin of Meeting A as a normal user of meeting B.

So this user has all permissions in meeting A but only the standard permissions in meeting B. As a normal user in Meeting B, he is not allowed to see the original motion. But with his permissions in meeting A, he is allowed to see the [restriction mode A](https://github.com/OpenSlides/openslides-autoupdate-service/blob/cb494e653cdd9b02c90f23a0f2fde3968bbc6e24/internal/restrict/field_def.go#L612-L624) of the original Motion in meeting B.

When the client requests all motions in meeting B, the original Motion is returned. But when the client accesses the content of the motion, then no data is returned.

I think the client needs some logic to decide, when a motion can be opened. It could only show the motion, if the user is allowed to see a [field in restriction mode C](https://github.com/OpenSlides/openslides-autoupdate-service/blob/cb494e653cdd9b02c90f23a0f2fde3968bbc6e24/internal/restrict/field_def.go#L625-L658)?

**Comment by bastianjoel** [comment]
More detailed reproduction steps:
1. Login as superadmin
2. Create account
3. Create committee
4. Edit committee and set can forward/receive from itself
5. Create two meetings (A, B) with previously created user as meeting admin
6. Open meeting A
7. go to motions > three-dot-menu > workflows > simple workflow > status submitted > change restrictions to submitters
8. Login as meeting admin, open meeting B
7. go to motions > three-dot-menu > workflows > simple workflow > status submitted > Allow forwarding of motions
10. Create motion
11. Forward to meeting A
12. Open motion in meeting A

As far is I understand a meeting admin should now be able to see all motion fields. Otherwise only superadmins would be able to accept incomming forwarded motions.

**Comment by ostcar** [comment]
Thank you. That helped. I can reproduce it. I don't get the `undefined` message, but you are correct, that the meeting admin can not see the motion text.

This is currently the expected behavior. This is the current description of the restrictor: 

https://github.com/OpenSlides/openslides-autoupdate-service/blob/091ea99128b4f425fede9341ce3b9c14fa59017e/internal/restrict/collection/motion.go#L17-L20

To see a motion, the user has to have the permission `motion.can_see` AND he has to fit the state restriction. There is currently no exception for an admin or a `motion.can_manage`.

This means, that currently, a meeting admin can not see a motion with the restriction to submitters.

To fix this, I would propose to change the motion restriction. A user with `motion.can_manage` can see all motions independent of the restrictions. 

Is this ok for you?

**Comment by ostcar** [comment]
I think the Idea was a bit different. You can add a second restriction to the workflow "can manage motions". If you do so, then everything works fine. If we would change the motion restrictor, that every motion-manager can see all motions, then this other feature would me useless.

**Comment by bastianjoel** [comment]
No it would not be useless. The restriction would only be ignored for forwarded motions. Motions that were created within the current meeting should still be hidden.

**Comment by jsangmeister** [comment]
I think the problem here is that for forwarded motions, it is currently not precisely defined who the submitter is. When a motion is forwarded, a dummy "committee user" is created for the forwarding committee with the same name which is then used as the submitter for the new motion. So, by that logic, the whole committee is the submitter of the motion. On the other hand, a motion is forwarded from a specific meeting, so one could also argue that only that meeting is the submitter.

I think the solution to your problem is that we must define who the submitter is and then handle the restriction strictly by how we defined it - that means that if a motion is restricted so that only submitters can see it, we must evaluate differently who a submitter is for forwarded motions. The two options are, as described above:
- either all users with `motion.can_forward` in the source _committee_
- or all users with `motion.can_forward` in the source _meeting_

I chose `motion.can_forward` as the needed permission since if a user can forward a motion, he or she should be able to see it afterwards.

What are your thoughts?
