### ISSUE TITLE
Reduce AU-subscriptions to improve performance while voting

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1995]
During a running poll the client starts subscriptions for the voting progress that are unnecessary for delegates.
We should reduce the amount of subscriptions and remove the progressbar for delegates if not already done.

**Comment by jsangmeister** [comment]
On a similar note: I think the `has_voted` route is called too often, although I did not investigate this in detail. But the route is called when updates come in which have nothing to do with the poll.

**Comment by luisa-beerboom** [comment]
> remove the progressbar for delegates if not already done.

Progress bar is already not displayed for delegates

**Comment by luisa-beerboom** [comment]
> On a similar note: I think the `has_voted` route is called too often, although I did not investigate this in detail. But the route is called when updates come in which have nothing to do with the poll.

Seems to me like it is called in three cases:
1. Upon creation of the `ViewModel` => Once per poll (for just that poll)
2. When the active meeting id has changed => Every time the meeting changes for the entire list of polls in that meeting
3. When the `ViewModelListObservable` has changed (after emissions have stopped) => For the entire list of polls

Some thoughts:
1. I think we should only check that for polls that are currently running. If we can vote for the poll, we need to at least check when, while entering the meeting, we receive via autoupdate an already running poll, when we become able to vote while the poll is already running, and when we receive a new delegation voting right.
2. If we already have a positive response for this poll, we don't need to check again unless it is reset
3. Other than that, we currently have no choice but to basically check at random whether we have voted, since votes that we sent in other tabs won't be noticed otherwise. Perhaps there should be another method for that (maybe sending a message to oneself via ICC?)

**Comment by luisa-beerboom** [comment]
This seems like it should probably be it's own issue, though. Since it doesn't really relate to the autoupdate.

What do you think @jsangmeister ?

**Comment by bastianjoel** [comment]
> > remove the progressbar for delegates if not already done.
> 
> Progress bar is already not displayed for delegates

Also it seem like there is no data received from autoupdate as a delegate when somebody voted.

**Comment by luisa-beerboom** [comment]
> Also it seem like there is no data received from autoupdate as a delegate when somebody voted.

The corresponding field is restricted in the autoupdate so that is to be expected

**Comment by luisa-beerboom** [comment]
@rrenkert just asking because it seems rather unclear to me: What are the plans with this issue? How will we proceed?

**Comment by rrenkert** [comment]
We have improvements in #2065 and #2097. I will close here.
