### ISSUE TITLE
Feature: make WLAN access data projectable

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#2122]
`.../.../projectors/detail/...`

### Feature description
In the sidebar of the projector control it is possible to display the WLAN access data as a full screen message. If the field in the sidebar is expanded, then a button for projection is displayed. Similar to countdowns. It is also not possible to delete the message.

![Bildschirm­foto 2023-03-24 um 09 33 00](https://user-images.githubusercontent.com/23032204/227496660-396080fc-a401-4ac0-ba9d-9c24381ee707.png)

In the message is displayed:
- QR code
- Network (SSID)
- Password 
- Encryption

![Bildschirm­foto 2023-03-24 um 10 55 20](https://user-images.githubusercontent.com/23032204/227496747-001fe871-93b9-4ee2-aea5-cea2c0919922.png)

If no WLAN access data is entered under `.../.../settings/participants`, a note is displayed when the field is expanded: Enter access data in the settings so that they can be projected.

**Comment by luisa-beerboom** [comment]
Given that the slidedata is calculated in the autoupdate-service this will absolutely multi-service feature.

The wifi settings are saved in the `meeting` model which AFAIK already serves as a content object for the current list of speakers slide, so the autoupdate would probably need to recognize a new value for the projections `type` attribute in this case and return exactly the thee wifi settings in the content.

I don't know if there actually have to be any backend changes since the meeting model already has `projection_ids`. What do you think about this @r-peschke ?

The client would also have to register a new type of slide.

**Comment by luisa-beerboom** [comment]
Talked to @r-peschke this will probably not require backend changes
