### ISSUE TITLE
Projector problem: It is possible to scroll a motion text upwards away

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2152]
Description: If a motion is projected, it is possible to scroll the content out of the viewable frame by hitting the scroll up button quite fast. 

Reprodcution:
1. open a meeting
2. open motions and create a motion with several text lines
3. project the motion
4. go to projector and open the standard projector detail view
5. scroll down the motion a several times
6. now scroll up and hit the up button quite fast a few times until the motion disappears. 

What should happen:
It should not be possible to scroll the motion away by hitting the scroll-up button quite fast. The limit to scroll up should be the beginning of the text.

**Comment by jsangmeister** [comment]
The scroll is controlled by the backend action `projector.control_view`. Two possible solutions, which should probably be implemented both:
- disable the client button until the action result/AU has come in. This is already done for most other buttons so you e.g. don't accidentally import something twice. Another benefit is that a user will not click twice out of impatience and then be annoyed because it scrolled to far.
- Restrict the field `projector/scroll` to a minimum of 0 in the backend.

**Comment by rrenkert** [comment]
Backend fixed in OpenSlides/openslides-backend#1692. Closing here since client already implements the mentioned functionality.
