### ISSUE TITLE
TypeError in participant csv import

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#2182]
Try to import >10 participants via csv import: 

```
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at participant-import.service.ts:127:37
[..]
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at StaticMainImportHandler.resolveEntries (base-main-import-handler.ts:101:29)
```

Works with <= 10 participants.

**Comment by luisa-beerboom** [comment]
Tried it with 15 Participants => The errors didn't appear

There shouldn't be anything in the code that puts a limit to the amount of imported datasets, I can imagine that certain bugs could arise that cause it to stop working with 0, 1 or 2 sets of data, or with/without the presence of duplicates among the data, but 10 is a really random number. 

The place that seems to throw the upper error message is  the setup function for the import models, so it also can't be that the backend has some sort of exception that causes the client to receive an unexpected response.

The best I can do at the moment is to go and change the places that are throwing the errors, but without the ability to replicate the bug, we won't know if it is fixed.

**Comment by luisa-beerboom** [comment]
Update: The actual problem was that the csv file had duplicate lines (a few users were in there multiple times) and that as a result _somehow_ this weird behavior came to be.

It seems the client may not be checking whether the csv file is valid.

Usually I'd propose to try and check the validity of the file beforehand and then show a specific error message stating that the csv has errors, but given that we are planning to move the imports to the backend, I wonder if we should even bother fixing this at this point or just build it correctly in the backend. What do you think @rrenkert

**Comment by rrenkert** [comment]
The PR fixes the actual problem and lets the backend give the correct error message. That's ok for now. The backend implementation of the import should integrate this case in the preview.
