### ISSUE TITLE
After opening the detail view of an motion, "undefined" is displayed instead of the motion text

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#2198]
`.../.../motions/...`

### Bug description
- After opening the detail view of an motion, "undefined" is displayed instead of the motion text. A few seconds later the motion text is loaded - depending on the user's network/device, length of the text and size of the instance. This worries users and makes them assume the text has disappeared or something.
- According to Emanuel, this behavior seems to be a follow-up effect of the change made to the Auto Update service (motion texts are loaded only when the detail view is clicked)

### Expected behavior
- When the motion text is loading, a loading bar is displayed to make it clear to users: there's still something coming, it's loading, it's not gone.
- The loading bar is visible at the very top inside the motion text tile and across the entire width until the text is fully loaded.
- Please use @angular/material/progress-bar
  - color: ThemePalette = 'primary';
  - mode: ProgressBarMode = 'indeterminate';
  - value = 50;
  - bufferValue = 75;
- Like this

![Apr-13-2023 15-48-09](https://user-images.githubusercontent.com/23032204/231781362-b4a92e3e-1b8f-4777-9b8d-26feb8592357.gif)

### Additional context
OpenSlides: → 4.0.1-main-20230405-096d7db

**Comment by luisa-beerboom** [comment]
Investigated the origin of this text: 
This `undefined` text comes from the `html` input of the `MotionDetailOriginalChangeRecommendationsComponent`, which is used on ln 113 of the `motion-detail-diff.component.html`
It is generated in the `LineNumberingService`s `insertLineNumbers` function when its `html` parameter is undefined.

It is undefined because this block: 
```
        if (this.motion.isParagraphBasedAmendment()) {
            try {
                baseText = this.motionLineNumbering
                    .getAllAmendmentParagraphsWithOriginalLineNumbers(this.motion, this.lineLength, true)
                    .join(`\n`);
            } catch (e) {
                console.error(e);
                return ``;
            }
        } else {
```
in the `motion-detail-dff.component.ts`s `getTextRemainderAfterLastChange` function probably generates it as such.

Anyway. The easiest way to fix this would probably be to just find out the conditions for this behaviour, somehow catch them in the `MotionDetailOriginalChangeRecommendationsComponent` and then showing the progress bar while one is still waiting.
