### ISSUE TITLE
Use `assignment/open_posts` as default value for `poll/max_votes_amount` when creating an assignment poll

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2235]
see https://github.com/OpenSlides/openslides-vote-service/issues/202 for more infos.

**Comment by emanuelschuetze** [comment]
see https://github.com/OpenSlides/openslides-vote-service/issues/202

"
[..]
I don't like the suggestion to use open_posts for max_votes_amount for all new assignment polls because this does not support runoff votes (e.g. 2nd or 3rd ballots). Then the max_votes_amount changes for each ballot. The open_posts will be unchanged for the whole election.
"
