### ISSUE TITLE
Projected image has wrong link in autopilot

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2260]
**Description:** If an image is projected in the Autopilot, the title links to the dashboard and not to the image. 

For example: The title link is bild_500x200.jpg
![Screenshot_20230508_102853](https://user-images.githubusercontent.com/105491030/236775368-8fc10ae0-56f2-4934-bfab-e8fc50e6c8c7.png)

**Reproduction:**
1. open a meeting
2. open **files** > upload an image
3. click on the three-dot-menu behind the image and choose _Project_
4. go to the Autopilot
5. Click on the title -> Dashboard opens

**What should happen?**
I'm a bit ambivalent, what solution would be the best. 
- First option: Open the image in the current tab. It would have the same behavior like opening a motion for example. 
- Second option: Open the image in another tab. It would have the same behavior like clicking on the projector. 

Both solutions are fine. But to be more consistence to the title link behavior in general, I would prefer the first option: The image should open in the same tab.

**Comment by jsangmeister** [comment]
I'm more in favor of the second solution: Mediafiles always open in a new tab in OpenSlides, since you are no longer "in the application", so to speak - you do not have the menu bar on the left and cannot navigate back to the projector except by pressing the back button. The same happens when opening a mediafile (or even the same image) in the mediafiles list. So for consistency an better UX, the image should open in a new tab
