### ISSUE TITLE
Error: No active meeting to query the structured relation

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#238]
This error appears when:
1. Login
2. Navigating from dashboard to a meeting (e.g. `meeting/1`)
3. Navigating to `user-list`
4. Navigating back to the dashboard 

![failure](https://user-images.githubusercontent.com/10206688/120482306-49388280-c3b1-11eb-8711-920d11fa7a13.png)

**Comment by FinnStutzenstein** [comment]
There must happen a view update while navigating (or shortly before). I can reproduce it. Some ways o fixing it:
1) just do not throw an error (https://github.com/OpenSlides/openslides-client/blob/master/client/src/app/core/repositories/users/user-repository.service.ts#L315 and in the relation manager) and return null. I do not like it since it currently also prevents for programming mistakes
2) fix the angular view-updating. Might be hard up to infeasible.

**Comment by GabrielInTheWorld** [comment]
It happens especially if `ViewUser.groups()` is called. 
These components do this:
- UserListComponent
- UserDetailComponent
