### ISSUE TITLE
[RTF] Search bar in (for example) List of speakers: new created user won't appear on LoS

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2615]
**Description:** If a user wants to create a new user in the List of speakers, the new user will be created, but won't appear on the list of speakers.

Important Note: This also affects the user search bar in Elections. I assume, that this is the same failure. 

In the console an error appears after user creation:
Error: Speaker creation failed: Selected user may not be in meeting

**Reproduction on RTF:**
1. open a meeting
2. open agenda > create a new topic > project it
3. open autopilot > use the user search bar and enter a new user name > create it 

**What should happen:**
The new created user should appear in the List of speakers after creation process.

**Comment by luisa-beerboom** [comment]
The problem is that the client creates the user via the user.create action, which, after creating the user, returns the user-id.
The client, having not loaded the full user yet, formerly just used that id to call speaker.create, however in rtf that action now requires the meeting_user-id, which the client doesn't have.
The client will then try to find the meeting_user-id in it's datastore, but fail since it hasn't loaded yet, hence the error.

To make this work there are 3 options:
1. (backend required) Change the speaker.create payload to work with the user-id again, or
2. (backend required) Change the user.create action to return `{ id: number; meeting_user_id?: number}` instead of `{ id: number}` so that the client may immediately interact with the meeting_user as well
3. (ugly, circuitous and impractical for big meetings with large autoupdate delays) Make a fetch request to get the meeting_user_id for the user model
What do you think about this @reiterl ?

**Comment by luisa-beerboom** [comment]
Talked with @reiterl : We're trying option 2 (change user.create) for now
