### ISSUE TITLE
Account deletion: speech in LoS is deleted

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2639]
**Description:** 
If a user does a speech during a meeting, it is recorded in the topic LoS. If the user account will be deleted, the reference in the LoS will also be deleted without a reference like anonymous user with XYZ speech time.

**Reproduction:**
1. open a meeting
2. open Agenda > create a new topic > project it to Autopilot
3. open participants > create a new user
4. open Autopilot > add new user to LoS > Start and Stop speech > now a reference of the speech is listed
5. open the organization level
6. open Accounts > delete new created user
7. head back to the meeting > Autopilot > reference is no more available

**What should happen:**
The speech reference should be available even after account deletion. The reference should be "deleted user + metadata of speech". Without that, the protocol of the meeting will lost important data. 

Another alternative for a reference will be to display "Anonymous user" instead of "deleted user".

**Comment by luisa-beerboom** [comment]
It seems that deleting the user causes the autoupdate to not deliver the corresponding speaker_id anymore.
This can mean one of two things:
1. This is an autoupdate restrictor problem, or
2. This is because of some sort of cascade delete in the backend.

Since it is probably the latter, I'll create a backend issue.

The client will then only have to be edited so that the `ViewSpeaker`'s `getTitle` method returns "Deleted user" if there is no linked user

**Comment by luisa-beerboom** [comment]
Backend issue is OpenSlides/openslides-backend#1917

**Comment by luisa-beerboom** [comment]
If a user is removed from the meeting, but is still present in orga and his meeting user is part of the speaker list, his name should still be visible in the speaker list.

This may not be the case right away, since the meeting_user may be filtered out for not having any groups, breaking the link between the speaker and the user. You may have to employ one of the repositories `unsafe` getter functions to get the MeetingUser and, from there, the user
