### ISSUE TITLE
Fix missing user_ids for supporters

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2669]
**Description:**
If supporters are added by an admin (not by the supporter themselves) then the the supporter's names but different names are displayed

**How to recreate:**
In a metting: 
1. settings > motions > supporters > Number of (min) required supporters [..] has to be one or bigger
2.  motions > New motion > select some participants as supporters, save motion
3. look at the lsit of supporters from the motion

**Send request from an updated motion:**
![motion update](https://github.com/OpenSlides/openslides-client/assets/69210919/74fee306-a07e-4b16-96fb-88b8d0c9a51d)

Ths as a supporter displayed account is not in the meeting and has the id: 2923

**Wanted behaviour:**
The correct supporters should be displayed in a motion

**Comment by Elblinator** [comment]
the request sends the correct ids but the motion-detail shows the wrong people

**Comment by luisa-beerboom** [comment]
> the request sends the correct ids but the motion-detail shows the wrong people
> 
> the wrong people are also displayed in the pdf

No the request doesn't send the correct ids:
The request should contain the `meeting_user_ids`, but the `user_ids` are sent instead.

So: 
If user A has `user_id === 2` and `meeting_user_id === 4` in this meeting 
and if user B has `user_id === 4` and `meeting_user_id === 5` in this meeting
and user B is selected, this is going to cause B's `user_id` to be sent, which the backend will then interpret as a `meeting_user_id` just to find user A.
So that is what's happening.
