### ISSUE TITLE
Fix deleted but still displayed topic

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2731]
**Current behaviour:**
If you delete a topic in topic detail, then the topic is still visible until a reload

**Reproduction:**
1. create a topic
2. navigate into topic-detail
3. delete the topic
4. you get thrown back to topics and the deleted topic is still visible

**Wanted behaviour:**
the topic should immediately disappear

**Comment by luisa-beerboom** [comment]
Can't replicate.
Please check if this is still happening and give a more detailed description @Elblinator .
Also, if it is still happening, it may be because the deletion-autoupdate simply hasn't been sent yet (because the topic-list can't know the new state until that autoupdate). So please also check if that is the case.

**Comment by Elblinator** [comment]
This really doesn't happen anymore 
Issue will be closed
