### ISSUE TITLE
Customizable global colors

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#279]
Maybe its a good feature to choose custom colors for poll-results.

**Comment by luisa-beerboom** [comment]
This will definitely require changes in the backend.
Before we make an issue over there we should discuss how this should work, however.

A couple of questions:
1. How will we persist these colours?
   1. Should the poll colours be handled individually for each poll(-option) (i.e. creating a new field in the options or poll model)?
   2. Should they be saved in the form of their own models (similar to themes) so that they're customizable centrally and can be assigned individually (individually by meeting, maybe even individually per poll)
   3. Should we just tie them to the themes?
2. We need to differentiate between the topic polls and the other types:
   1. Normal polls need three colours: One for yes, no and abstain each.
   2. Topic polls typically use a list of colours and then a repeating range of predetermined greys 
      - Being able to choose a custom colour for each option may be particularly helpful here
      - If we're using central themes instead, we would have to make a differentiation: We could either do separate theme models for topic and other polls or make unified themes that contain customizable colour options for both

What do you think would be better @emanuelschuetze  @rrenkert ?

**Comment by emanuelschuetze** [comment]
We need 3 custom color options for Yes/No/Abstain - in motions and assignment polls.
Defined in global design view.

Additional: custom color for _global_ headbar, if not set use a generated color value (currently)

**Comment by luisa-beerboom** [comment]
Backend issue: OpenSlides/openslides-backend#1671
