### ISSUE TITLE
Motion and projection of it with wrong line numbers (amendment vs. change recom. at same position)

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2903]
**Description:** If a motion has a change recommendation and an amendment at the same paragraph position, the line numbering in motion view and in the projection is wrong. As you see in the first image, the line of the second change (her change recommendation) starts with 2 and in the second image - the projection - with 6. This is wrong.  

Motion view:
![Screenshot_20231017_145009](https://github.com/OpenSlides/openslides-client/assets/105491030/87efd240-a4db-49a8-80d2-9a53f2dcd31a)

Projection:
![Screenshot_20231017_143415](https://github.com/OpenSlides/openslides-client/assets/105491030/f7200426-4196-49c4-b2cf-e24c81f7d5cd)

**Reproduction:**
1. open a meeting
2. open motions
3. create a motion with one paragraph with a few lines.
4. create a change recommendation and accept it
5. create an amendment which changes the whole paragraph and change state to accepted (not sure if needed, but it shows it quite well)
6. now both changes should be in conflict
7. project the motion in diff version

**What should happen:**
The lines of each paragraph should start at number 1, because the content of the changes is in conflict and did not follow each other, which would justify an ongoing numbering.

**Comment by Elblinator** [comment]
The behaviour of the projection potentially changed due to the Issue #2880, please verify that the buggy behaviour is still there
Additionally: 
Just to be clear: If one paragraph was changed two times by an amendment or a change recommendation and these changes are in conflict to each other. Then the whole paragraph should be displayed two times in the projection. Not just the conflicting lines?
@MSoeb @emanuelschuetze

**Comment by MSoeb** [comment]
Re-Tested: The problem didn't occur anymore. It is solved. 
@Elblinator Your question is still relevant, but it isn't important for this bug.

-> Issue closed
