### ISSUE TITLE
Fix wrong routing of reset-link

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3068]
**Current behaviour:**
If a reset-link is sent and you try to open the link then it can happen that you are directed to the normal login-page and not the reset-password-page

**Reproduction:**
(your openslides needs a working mail-server)
1. create an account with mail address 
2. log out 
3. send a reset link 
4. open an incognito-tab
5. open the reset-link in incognito
6. you are potentially navigated to the reset-password-link OR the login-page

**Wanted behaviour:**
the reset-link should navigate you to the reset-password-link

**Comment by luisa-beerboom** [comment]
I tried replicating this in the dev environment by entering a fake link with a fake id and fake token, but I didn't actually manage to get the proper reset page even once. It always relocates me to the login page whether I used incognito mode or not, with no indication, neither in code nor in console, as to why this happens.

Therefore I could, so far, neither trace this back to the guards, nor the routing, nor the `ResetPasswordConfirmComponent` (which were my best guesses when it comes to the source of the problem).

I was a bit perplexed that the link seems to contain two `/`s before the actual path, but since it still seems to work sometimes that probably isn't the issue here.

So yeah, still a massive question mark for me
@bastianjoel , could you take a look as well?
