### ISSUE TITLE
The ballot election handling is missleading

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-client#3286]
The ballot election handling is missleading
It shows an "Submit vote" button. But after clicking on the "thumb up" of one candidate, it gives me prompt and sends the vote, *without* using the submit button.

**Comment by luisa-beerboom** [comment]
The dialog shows up whenever a user has clicked as many options as he is allowed to.
This is practical since, if you are on a 30-option election and click the first one, you don't have to scroll down all the way to the bottom.

So why have the bottom button? Because of the poll settings `min_vote` and `max_vote` that allow one to define something like "Users have to choose between 3 and 5 options". If I am allowed up to 5 options, but also permitted to submit less, I need a way to submit when I only have 3 options. And that's what the button is for.

Given that the button doesn't hurt anyone, even if there is no variance in option number allowed, and that the dialogue isn't exactly much of a bother either (it's not like you _have_ to affirm sending the vote, you can still deny and either change things or send via the button), I'd advocate for keeping things as they are.

**Comment by reiterl** [comment]
Okay, I understand this. Closed with "won't fix/ no bug"
