### ISSUE TITLE
Changing of underlying models

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#358]
I have noticed that there are some "container"-models (like polls or projectors), which are requested. These models are not updated in the view, if underlying models (like options/votes or projections) are changed.
Here, we need a routine to deal with this behaviour.

**Comment by FinnStutzenstein** [comment]
See https://github.com/OpenSlides/openslides-client/pull/349

The behavior is indended. In the example above one have a projector given and wants all `current_projections`. If a projection gets an update (not the relation itself, which would trigger an update for the projector), only the projection is updated. So the projector explicitly does not get an update. This is wanted since otherwise, we would have to trigger everything on an update, since every model is with some relations connected to every other model.

**Comment by GabrielInTheWorld** [comment]
I think, this can be closed in favor of #349.
