### ISSUE TITLE
superadmin who is not in meeting does not have all permission

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#363]
If the superadmin was removed from a meeting, they can still access it yet cannot make changes since the permissions seem to be equal to "default". I suppose since the view user was missing from the operator even `this.hasOrganizationPermissions()` was not fired.

**Comment by GabrielInTheWorld** [comment]
What is your expected bavhiour? Should a superadmin have still all permissions even though it is not associated to a meeting anymore or should it not have access to the meeting?

**Comment by tsiegleauq** [comment]
According to @emanuelschuetze this would be the intended behavior. As a superadmin, one should be able to see, create and edit all data inside a meeting although they are not directly associated. This might be a challenge for our operator service

**Comment by GabrielInTheWorld** [comment]
The permission-checks within a meeting are always belonging to the meeting's groups. A user, who is removed from a meeting has no associated group and therefore in the default group of a meeting.
Well, in a first thought I have two approaches how this can be accomplished:

1. The "mallet" method: In every permission-check, we could check if one is a "superadmin" (regardless of their assigned group in a meeting). This is the simplest method and my preferred way.
2. Otherwise the backend has to check, if a user is removed from a meeting, if this user is a superadmin and then it still assigned to the admin-group of the meeting. But I think, this approach would entail further complications...
