### ISSUE TITLE
Allow meetings admins to change personal information for certain users

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3841]
see for context: https://github.com/OpenSlides/openslides-backend/issues/2522

**Current behaviour:**
If a user (Ann) is a meeting admin (more precise when Ann is allowed to manage participants) in two meetings and another user (Ben) is only in these two meetings then Ann is currently not allowed to change the personal information from this user.
Currently Ann can still change the personal information but not save it. After the PR #3833 is mergen Ann is not even allowed to change the information in the edit mask from this user.

**Wanted behaviour:**
As long as Ann is allowed to manage participants in every meeting Ben is a participant in then Ann is allowed to change Ben's personal information

**Comment by Elblinator** [comment]
The presenter was changed, please look into the backend PR/ descriptions for more details

**Comment by reiterl** [comment]
What is the name of this new presenter? Then I can look at the presenter documentation.

**Comment by reiterl** [comment]
The new presenter is the `get_user_editable` presenter.
All personal information are of the same permission group in the user.update action (Group A).
This issue is only about the participant-detail view.

I think I will include the presenter in the `UserService` with one id and just a represent of the group A fields
and disable the Personal Information fields.
