### ISSUE TITLE
Regression after #492 - committee create form hangs on XHR

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#506]
Since #492 the committee create form has a chance to hang on xhr requests. Integration tests are failing completely.

Affected commit:
114d9006bafc991362575b99eecb7ab83a4e2a13

**Comment by GabrielInTheWorld** [comment]
Why do you think, that this specific commit causes the hanging?
I'm asking, because the affected lines in the `CommitteeEditComponent`, that are changed in #492, are changed in #482 again...

Another question is, is this still the case with the current master (0da1a9ab297db57094ca70143ff6abc15863f7f6)?
