### ISSUE TITLE
string configs are `undefined` in type

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#742]
In the meeting settings field component, all "string" configs are undefined. Thus translations cannot be applied.
The hotfix would be to respect `undefined` in the if-condition, but we should find out why `setting.type` does not include string anymore.

```js
this.translatedValue = this.value ?? this.meetingSettingsDefinitionProvider.getDefaultValue(this.setting);
console.log(`vv :`, this.setting.type);
if (this.setting.type === `string` || this.setting.type === `markupText` || this.setting.type === `text`) {
    if (typeof this.value === `string` && this.value !== ``) {
        console.log(`vv this.value: `, this.value);
        this.translatedValue = this.translate.instant(this.value);
        console.log(`vv translatedValue: `, this.translatedValue);
    }
}
```

**Comment by luisa-beerboom** [comment]
The reason it does not include `string` is because the `type` property is optional.
I think this "workaround" is fine as is. It basically is just a way to create a default value for the type and avoid having to unnecessarily write a specific type-value into the definition of every field.

What do you think @rrenkert

**Comment by jsangmeister** [comment]
Alternatively, you could replace the current `meetingSettings` object with a function to access it, which injects `type = text` for all these settings. I think this would be the cleaner approach.
